FROM node:16-alpine
  
RUN mkdir -p /usr/app
WORKDIR /usr/app

# Install dependencies based on the preferred package manager
COPY ./ ./

RUN npm i
RUN npm run build

EXPOSE 3000

CMD ["npm","run", "start"]
